var CONFIG = {
    TIMEOUT: 60,
    //MODULE_DEFAULT: 'md-menu1.1',
    MODULE_DEFAULT: 'md-blank',
    MAX_BUFFER_MESSAGE: 10,
    TIMEOUT_RETRY_WS: 1000,
    URL_WEBSOCKET: 'ws://localhost:8080/',
    URL_API: 'http://localhost:8080/',
    BROADCAST_STATE: 'BROADCAST_STATE',
    BROADCAST_MESSAGE: 'BROADCAST_MESSAGE',
};